page_blog/blog/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name='blog'
urlpatterns = [
    path('', login_required(views.AllPostView.as_view()), name='main'),
    path('create/', login_required(views.PostCreateView.as_view()), name='create'),
    path('detail/<int:pk>/', login_required(views.PostDetailView.as_view()), name='detail'),
    # path('detail/<int:pk>/comment', views.comment_view)
]

# urlpatterns = [
#     path('', views.main, name='main'),
#     path('login/', views.login, name='login'),
#     path('register/', views.register, name='register'),
#     path('create/', views.create, name='create'),
#     path('<int:post_id>/detail/', views.detail, name='detail'),
# ]

page_blog/page_blog/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views

urlpatterns = [
    path('', include('blog.urls'), name='main'), 
    path('register/', user_views.register , name='register'),
    path('profile/', user_views.profile , name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html') , name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html') , name='logout'),
    path('admin/', admin.site.urls),
]

page_blog/blog/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.shortcuts import reverse

class User(models.Model):
    email = models.EmailField(max_length =70, blank = True)
    pswd = models.CharField(max_length=70, blank=True)

    def __str__(self):
        return self.email

class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=50, blank=True)
    publish_time = models.DateTimeField('Date Published')
    content = models.TextField(default=timezone.now)

    # def get_absolute_url(self):
    #     return reverse('blog:detail', kwargs={'pk':self.pk}) # აქ მოდის HTML_ში არსებული pk და აბრუნებს შესაბამის პოსტს
        # და ამ პოსტს აგზავნის detail ის url _ზე

    def __str__(self):
        return self.title


class Comment(models.Model):
    comm_author = models.ForeignKey(User, on_delete=models.CASCADE)
    publish_time = models.DateTimeField('Date Published')
    content = models.TextField(default=timezone.now)
    on_post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.comm_author)

page_blog/users/models.py
from django.db import models

# Create your models here.

page_blog/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

page_blog/blog/views.py
from .models import User, Post, Comment
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from django.urls import reverse
from django.views import generic
from django.http import HttpResponse ,HttpResponseRedirect
from django.contrib.auth.decorators import login_required


class PostCreateView(generic.DetailView):
    model = Post # მოაქვს მოდელი და ამ მოდელის ობიექტები


class AllPostView(generic.ListView):
    template_name = 'blog/main.html'
    context_object_name = 'homeposts' # მოაქვს ყველა ობიექტი

    def get_queryset(self):
        return Post.objects.filter(publish_time__lte=timezone.now()).order_by('-publish_time')
    
    # def get_queryset(self):
    #     return Post.content(max_length = 20)


class PostDetailView(generic.DetailView):
    template_name = 'blog/detail.html'
    # pk_url_kwarg = 'pk' # აქ მოდის pk_ს შესაბამისი პოსტი
    model = Post
    context_object_name = 'posts'

    
    def get_context_data(self, **kw):
        context = super().get_context_data(**kw) # 
        post = self.get_object()
        context['comments'] = Comment.objects.filter(on_post=post)
        context['other_posts'] = Post.objects.filter(author=post.author).exclude(title=post.title)
        return context

# def comment_view(request, pk):
#     comm = get_object_or_404(Comment,pk=pk)
#     return render(request, 'blog/detail.html', {'comm':comm})

page_blog/users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm
# from django.contrib.auth 

def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, 'Account has been created! You should Log in in your account!')
            return redirect('users:login')

    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form':form})

@login_required
def profile(request):
    return render (request, 'users/profile.html')

page_blog/blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% if title %}
        <title>Django-Blog - {{ title }}</title>
    {% else %}
        <title>Django-Blog</title>
    {% endif %}
</head>
<body>
    <div>
        <h1>
            <a href="{% url 'blog:main' %}">BLOG</a>
        </h1>
    </div>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
    {%endif%}
    {% if user.is_authenticated %}
        <a class="nav-item nav-link" href="{% url 'logout' %}">Log out</a>
        <p>
            <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
        </p>
    {% else %}
        <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
        <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
    {% endif %}
    {% block content %}{% endblock %}
</body>
</html>

page_blog/blog/templates/blog/detail.html
{% extends "blog/base.html" %}
{% block content %}
    <article class="media content-section">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="#">{{ posts.author }}</a>
                <small class="text-muted">{{ posts.publish_time|date:"F d, Y f A" }}</small>
            </div>
            <h2><a class="article-title"><h1>{{ posts.title }}</h1></a></h2>
            <p class="article-content">{{ posts.content }}</p>
        </div>
    </article>  
    {% for comment in comments %}
        <p>By {{ comment.comm_author }} on {{ comment.publish_time }}</p>
        <p>{{ comment.content }}</p>
    {% endfor %}

    {% for other_post in other_posts %}
        {{other_post}}
    {% endfor %}
    <div>
        
    </div>
   
{% endblock content %}

page_blog/blog/templates/blog/main.html
{% extends "blog/base.html" %}
{% block content  %}
    {% if homeposts %}
    <ul>
    {% for post in homeposts %} <!-- შევედით ბაზაში კონკრეტულად პოსტების მოდელში -->
        <li>
            <h1><a href="{% url 'blog:detail' post.id %}"> {{ post.title }} </a></h1> <!--post.id_ს აწვდის URLpattern_ში ცვლად pk_ას-->
        </li>
        <p>By {{ post.author }} on {{ post.publish_time|date:"F d, Y f A" }}</p>

        <p>{{post.content|slice:'50'}}...</p>
    {% endfor %}
    </ul>
    {% else %}
        <p></b> Sorry There is no any Posts </b></p>
    {% endif %}
{% endblock content %}

page_blog/users/templates/users/login.html
{% extends 'blog/base.html' %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                {{ form.as_p }} <!--ანუ ეს რეგისტრაციის ფორმს გამოიტანს როგორც პარაგრაფს კარგად რო გამოჩნდეს. მოდის views ში შექმნილი მეთოდიდან-->
            </fieldset>
            <div class="fomr-group">
                <button class="btn btn-outline-info" type="submit">Login</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                    Need an Account ? <a class="ml-2" href="{% url 'register' %}"> Sing Up now </a>
            </small>
        </div>
    </div>
{% endblock content %}

page_blog/users/templates/users/logout.html
{% extends 'blog/base.html' %}
{% block content %}
    <div class="content-section">
            <h2>
                You Have been logged out!
            </h2>
        <div class="border-top pt-3">
            <small class="text-muted">
                <a href="{% url 'login' %}"> Log in again </a>
            </small>
        </div>
    </div>
{% endblock content %}

page_blog/users/templates/users/profile.html
{% extends 'blog/base.html' %}
{% block content %}
    <h1>{{ user.username }}</h1>
{% endblock content %}

page_blog/users/templates/users/register.html
{% extends 'blog/base.html' %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                {{ form.as_p }} <!--ანუ ეს რეგისტრაციის ფორმს გამოიტანს როგორც პარაგრაფს კარგად რო გამოჩნდეს. მოდის views ში შექმნილი მეთოდიდან-->
            </fieldset>
            <div class="fomr-group">
                <button class="btn btn-outline-info" type="submit">Sign up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                <a class="ml-2" href="{% url 'login' %}"> Already have an Account ? </a>
            </small>
        </div>
    </div>
{% endblock content %}